server:
  port: 8762
spring:
  application:
    name: provider
eureka:
  environment: dev
  instance:
    appname: cloud provider
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
